// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrmgcdqgeguiqjunjefx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlybWdjZHFnZWd1aXFqdW5qZWZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTg0NDUsImV4cCI6MjA2OTM3NDQ0NX0.k5lwIZH6skKMp5sD8yq8tkNR-h5ZBa8w97MQ-uFlt44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});